apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "file-manager-server.fullname" . }}-http
  labels:
    {{- include "file-manager-server.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  {{- with .Values.global.ingress.tls }}
  tls:
  - hosts:
      {{- toYaml .hosts | nindent 6 }}
    {{- if .secretName }}
    secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /v1/files
        pathType: Prefix
        backend:
          service:
            name: {{ include "file-manager-server.fullname" . }}-http
            port:
              number: {{ .Values.httpPort }}

---

{{- if .Values.global.workerServiceIngress.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "file-manager-server.fullname" . }}-worker-service-grpc
  labels:
    {{- include "file-manager-server.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.workerServiceIngress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  {{- with .Values.global.ingress.tls }}
  tls:
  - hosts:
      {{- toYaml .hosts | nindent 6 }}
    {{- if .secretName }}
    secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /llmoperator.files.server.v1.FilesWorkerService
        pathType: Prefix
        backend:
          service:
            name: {{ include "file-manager-server.fullname" . }}-worker-service-grpc
            port:
              number: {{ .Values.workerServiceGrpcPort }}
      - path: /llmariner.files.server.v1.FilesWorkerService
        pathType: Prefix
        backend:
          service:
            name: {{ include "file-manager-server.fullname" . }}-worker-service-grpc
            port:
              number: {{ .Values.workerServiceGrpcPort }}
{{- end -}}
