httpPort: 8080
grpcPort: 8081
internalGrpcPort: 8082

global:
  objectStore:
    s3:
      endpointUrl:
      bucket:

  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:

  ingress:
    ingressClassName:

  database:
    host:
    port:
    username:
    passwordEnvName:

objectStore:
  s3:
    pathPrefix: files

database:
  database: file_manager

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/file-manager-server
  pullPolicy: IfNotPresent

version:
